### ISSUE TITLE
Improve loading time for images

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/prep-portfolio-22.OCT.PREP.2#2]
Currently, images take a while to load as they're quite large. Can we compress the images when they are committed using a GitHub action to improve loading speeds?

**Comment by Kunalpal215** [comment]
If I am not wrong then, image compression needs to be done when there is a pull request to the repository right ?

**Comment by Kunalpal215** [comment]
I am saying this as I am not able to find any suitable workflow in marketplace which will compress image when they are pushed.
